---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: notejam-stagin
  region: sa-east-1
  version: "1.21"

managedNodeGroups:
- name: nodegroup
  desiredCapacity: 3
  instanceType: t3.micro
  ssh:
    publicKeyName: notejam