---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: notejam
  region: sa-east-1
  version: "1.21"


managedNodeGroups:
- name: nodegroup
  desiredCapacity: 3
  instanceType: t3.micro
  ssh:
    publicKeyName: notejam 

# To enable all of the control plane logs, uncomment below:
# cloudWatch:
#  clusterLogging:
#    enableTypes: ["*"]


  