version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: circleci/python:3.8.10
    steps:
      - checkout
      - run:
          name: build jobs
          command: exit 0;
