apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  labels:
    app: {{ .Values.app.name }}
  namespace: default
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
      - name: {{ .Values.app.name }}
        image: {{ .Values.app.image }}:{{ .Values.app.tag }}
        imagePullPolicy: Always
        env:
          - name: DB_USER
            value: "{{.Values.app.DB_USER}}"
          - name: DB_PASS
            value: "{{.Values.app.DB_PASS}}"
          - name: DB_NAME
            value: "{{.Values.app.DB_NAME}}"
          - name: DB_PORT
            value: "{{.Values.app.DB_PORT}}"
          - name: DB_HOST
            value: "{{.Values.app.DB_HOST}}"
        ports:
        - containerPort:  {{ .Values.app.port }}
          protocol: TCP